Dev/alejoruiz
MatiusDev/Inventario-andalucia pull request #42
Opened 2024-12-10 02:03 UTC by alejandroruiz23

Nuevo: se agrega parte final del CRUD de proveedores (suppliers). Completamente funcional

Nuevo: CRUD de producto planta completo con código limpio

Nuevo: creación de servicio de notificación. Incluye entidad, modelo, servicio y controlador para mostrar mensajes guardados.
Prueba: se agregó servicio de notificación en la creación de un producto para probar su funcionamiento. 

Pendiente: acoplar con CRUD productos completo

2024-12-11 03:12 UTC, MatiusDev requested changes

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/controllers/plant_controller.py
> +    return await response_handler(plant_service.list_plant())
Revisar las redundancias de los metodos

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/controllers/product_controller.py
> +    return await product_service.get_all_plants()
Usar el response handler

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/models/entities/plant.py
> +    required_light: Light_Enum
No usar enums en el modelo de entidad

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/models/entities/product.py
> +  plant: "Plant" = Relationship(back_populates="products")
Agregar el # type: ignore

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/router/routes.py
>  routes.include_router(role_route, tags=["Roles"], prefix="/roles")
Quitar duplicados

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/services/notify_service.py
> +NotifyDependency = Annotated[NotifyService, Depends(NotifyService)]
SNotifyDependency

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/services/plant_service.py
> +            plants = self.db.exec(select(Plant)).all()
Devolver lo de la base de datos o un arreglo vacío

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/services/plant_service.py
> +            plant_data_dict = plant_data.model_dump(exclude_unset=True)
exclude_none, en el update_dump

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/services/plant_service.py
> +            plant_db = Plant.model_validate(plant_data.model_dump())
Hacer un create_dump

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/services/plant_service.py
> +                return { "status_code": 404, "detail": "Plant not found", "status": "fail" }
Mensajes de respuesta al cliente en español

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/services/plant_service.py
> +            return {"message": "Plant deleted", "status": "success"}
Mensaje en español

2024-12-11 03:12 UTC, MatiusDev commented on inventory_api/core/services/product_service.py
> +    return products
devolver estructura para usar response_handler

2024-12-13 02:48 UTC, alejandroruiz23 commented on inventory_api/core/controllers/plant_controller.py
> +    return await response_handler(plant_service.list_plant())
Corregido

2024-12-13 02:48 UTC, alejandroruiz23 commented on inventory_api/core/controllers/product_controller.py
> +    return await product_service.get_all_plants()
corregido y anexado

2024-12-13 02:49 UTC, alejandroruiz23 commented on inventory_api/core/models/entities/plant.py
> +    required_light: Light_Enum
Corregido

2024-12-13 02:49 UTC, alejandroruiz23 commented on inventory_api/core/models/entities/product.py
> +  plant: "Plant" = Relationship(back_populates="products")
corregido

2024-12-13 02:49 UTC, alejandroruiz23 commented on inventory_api/core/router/routes.py
>  routes.include_router(role_route, tags=["Roles"], prefix="/roles")
corregido

2024-12-13 02:49 UTC, alejandroruiz23 commented on inventory_api/core/services/notify_service.py
> +NotifyDependency = Annotated[NotifyService, Depends(NotifyService)]
Corregido

2024-12-13 02:49 UTC, alejandroruiz23 commented on inventory_api/core/services/plant_service.py
> +            plants = self.db.exec(select(Plant)).all()
corregido

2024-12-13 02:49 UTC, alejandroruiz23 commented on inventory_api/core/services/plant_service.py
> +            plant_db = Plant.model_validate(plant_data.model_dump())
corregido

2024-12-13 02:50 UTC, alejandroruiz23 commented on inventory_api/core/services/plant_service.py
> +                return { "status_code": 404, "detail": "Plant not found", "status": "fail" }
corregido

2024-12-13 02:50 UTC, alejandroruiz23 commented on inventory_api/core/services/plant_service.py
> +            return {"message": "Plant deleted", "status": "success"}
corregido

2024-12-13 02:50 UTC, alejandroruiz23 commented on inventory_api/core/services/product_service.py
> +    return products
corregido

2024-12-13 04:32 UTC, MatiusDev commented on inventory_api/core/controllers/product_controller.py
> +async def get_all_plants(product_service: SProductDependency):
get_all_tools

2024-12-13 04:34 UTC, MatiusDev approved these changes, later dismissed

2024-12-13 04:35 UTC, merged